CREATE TABLE `data_platform_payment_requisition_item_data`
(
  `PayerPaymentRequisitionID`            int(16) NOT NULL,
  `PayerPaymentRequisitionItem`          int(6) NOT NULL,
  `Payer`                                int(12) NOT NULL,
  `PayerPaymentDate`                     date NOT NULL,
  `SupplyChainRelationshipID`            int(16) NOT NULL,
  `SupplyChainRelationshipBillingID`     int(4) NOT NULL,
  `SupplyChainRelationshipPaymentID`     int(2) NOT NULL,
  `BillToParty`                          int(12) NOT NULL,
  `BillFromParty`                        int(12) NOT NULL,
  `Payee`                                int(12) NOT NULL,
  `Buyer`                                int(12) NOT NULL,
  `Seller`                               int(12) NOT NULL,
  `InvoiceDocument`                      int(16) DEFAULT NULL,
  `PayeeHouseBank`                       varchar(5) DEFAULT NULL,
  `PayeeHouseBankAccount`                varchar(5) DEFAULT NULL,
  `PayeeFinInstCountry`                  varchar(3) NOT NULL,
  `PayeeFinInstCode`                     varchar(10) NOT NULL,
  `PayeeFinInstBranchCode`               varchar(10) NOT NULL,
  `PayeeFinInstFullCode`                 varchar(15) NOT NULL,
  `PayeeFinInstSWIFTCode`                varchar(11) DEFAULT NULL,
  `PaytReqnItemAmtInTransCrcy`           float(13) NOT NULL,
  `PayeeInternalFinInstCustomerID`       int(12) NOT NULL,
  `PayeeInternalFinInstAccountID`        int(12) NOT NULL,
  `PayeeFinInstControlKey`               varchar(2) NOT NULL,
  `PayeeFinInstAccount`                  varchar(18) NOT NULL,
  `PayeeFinInstAccountName`              varchar(40) NOT NULL,
  `PayeeFinInstName`                     varchar(100) NOT NULL,
  `PayeeFinInstBranchName`               varchar(100) NOT NULL,
  `PayerAccountingDocument`              int(16) DEFAULT NULL,
  `PayerAccountingDocumentItem`          int(3) DEFAULT NULL,
  `CreationDate`                         date NOT NULL,
  `LastChangedDate`                      date NOT NULL,
  `IsCancelled`                          tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`PayerPaymentRequisitionID`, `PayerPaymentRequisitionItem`),

    CONSTRAINT `DPFMPaymentRequisitionItemData_fk` FOREIGN KEY (`PayerPaymentRequisitionID`) REFERENCES `data_platform_payment_requisition_header_data` (`PayerPaymentRequisitionID`),
    CONSTRAINT `DPFMPaymentRequisitionItemDataSCRPaymentID_fk` FOREIGN KEY (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `SupplyChainRelationshipPaymentID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`, `Payer`, `Payee`) REFERENCES `data_platform_scr_payment_relation_data` (`SupplyChainRelationshipID`, `SupplyChainRelationshipBillingID`, `SupplyChainRelationshipPaymentID`, `Buyer`, `Seller`, `BillToParty`, `BillFromParty`, `Payer`, `Payee`),
    CONSTRAINT `DPFMPaymentRequisitionItemDataInvoiceDocument_fk` FOREIGN KEY (`InvoiceDocument`) REFERENCES `data_platform_invoice_document_header_data` (`InvoiceDocument`),
    CONSTRAINT `DPFMPaymentRequisitionItemDataPayeeHouseBankAccount_fk` FOREIGN KEY (`Payee`) REFERENCES `data_platform_house_bank_house_bank_data` (`BusinessPartner`)

) ENGINE = InnoDB
DEFAULT CHARSET = utf8mb4;
